/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rfid;

import java.io.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Bayu
 */
public class Main extends javax.swing.JFrame {
    
    //object memuat data mahasiswa  
    Student dataStudent = new Student();
    
    //object memuat data dosen
    Lecturer dataLecturer = new Lecturer();
    
    //object memuat data ruangan, pengecekan jadwal dan lain lain untuk verifikasi tapping
    Room dataRoom = new Room();
    
    //object untuk data RFID Reader
    RFIDReader dataReader = new RFIDReader();
    
    //object untuk data IDCard ( ktm )
    IDCard ktm = new IDCard();
    
    //attribute nomor ruangan yang diinput
    String noRuang;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
        
    }
    
    //method mengecek apakah mahasiswa dengan nim yang diinputkan terdaftar atau tidak
    public boolean cek(String status, String indikator) {
        boolean cek = false;
        
        try {
            FileReader fr = new FileReader(status + ".txt");
            BufferedReader br = new BufferedReader(fr);
            String temp;
            while ((temp = br.readLine()) != null) {
                if (temp.substring(0, 10).equals(indikator)) {
                    cek = true;
                    //mengoper data dari class lecturer dan student
                    if (status.equals("mahasiswa")) {
                        dataStudent.setNim(temp.substring(0, 10));
                        dataStudent.setJurusan(temp.substring(11, 30));
                        dataStudent.setThnmasuk(temp.substring(31, 35));
                        dataStudent.setNama(temp.substring(45, temp.length()));
                    } else {
                        dataLecturer.setNip(temp.substring(0, 10));
                        dataLecturer.setJurusan(temp.substring(11, 30));
                        dataLecturer.setThnmasuk(temp.substring(31, 35));
                        dataLecturer.setNama(temp.substring(36, temp.length()));
                    }
                }
            }
        } catch (IOException e) {
            System.out.println("Error di : " + e);
        }
        return cek;
    }
    
    //menampilkan tanggal pada saat ini ( saat tapping )
    public String getDate() {
        Date date = new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("dd-M-yyyy");
        String strDate = formatter.format(date);
        return strDate;
    }
    
    //menampilkan waktu pada saat ini ( saat tapping )
    public String getTime() {
        Date date = new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("hh:mm:ss");
        String strTime = formatter.format(date);
        return strTime;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnCardDosen = new javax.swing.JButton();
        btnCardStudent = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnRFIDReader = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnTap = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RFID Application");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Choose ID Card");

        btnCardDosen.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btnCardDosen.setText("Lecturer");
        btnCardDosen.setMaximumSize(new java.awt.Dimension(80, 80));
        btnCardDosen.setMinimumSize(new java.awt.Dimension(80, 80));
        btnCardDosen.setPreferredSize(new java.awt.Dimension(80, 80));
        btnCardDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCardDosenActionPerformed(evt);
            }
        });

        btnCardStudent.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btnCardStudent.setText("Student");
        btnCardStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCardStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addComponent(btnCardDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCardStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCardDosen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCardStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Choose RFID Reader");

        btnRFIDReader.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnRFIDReader.setText("RFID Reader");
        btnRFIDReader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRFIDReaderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRFIDReader, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRFIDReader, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
        );

        btnTap.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        btnTap.setText("TAP NOW !");
        btnTap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTapActionPerformed(evt);
            }
        });

        btnHistory.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        btnHistory.setText("HISTORY");
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(btnTap, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTap, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCardStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCardStudentActionPerformed
        String inputan = JOptionPane.showInputDialog("Masukan NIM Mahasiswa");
        
        //mengoper data mahasiswa ke tampilan id card
        if (cek("mahasiswa", inputan)) {
            ktm.view("Mahasiswa", dataStudent.getNama(), dataStudent.getNim(), dataStudent.getJurusan(), dataStudent.getThnmasuk());
            ktm.setVisible(false);
            ktm.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "NIM Anda Tidak Ditemukan !", null, WIDTH, null);
        }
    }//GEN-LAST:event_btnCardStudentActionPerformed

    private void btnCardDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCardDosenActionPerformed
        String inputan = JOptionPane.showInputDialog("Masukan NIP Dosen");
        
        //mengoper data dosen ke tampilan id card
        if (cek("dosen", inputan)) {
            ktm.view("Dosen", dataLecturer.getNama(), dataLecturer.getNip(), dataLecturer.getJurusan(), dataLecturer.getThnmasuk());
            ktm.setVisible(false);
            ktm.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "NIP Anda Tidak Ditemukan !", null, WIDTH, null);
        }
    }//GEN-LAST:event_btnCardDosenActionPerformed

    private void btnTapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTapActionPerformed
        File dataLog = new File("log.txt");
        try {
            //membuat file log jika tidak ada
            if (!dataLog.exists()) {
                dataLog.createNewFile();
            }

            //cek koordinat
            boolean koordinat = (ktm.getX() >= dataReader.getX() && ktm.getX() <= (dataReader.getX() + dataReader.getWidth()) || 
                    (ktm.getX()+ktm.getWidth()) >= dataReader.getX() && (ktm.getX()+ktm.getWidth()) <= (dataReader.getX() + dataReader.getWidth()));        
            if (!koordinat) {
                JOptionPane.showMessageDialog(this, "Letakan posisi IDCard di RFIDReader !", null, WIDTH, null);
                return;
            }

            //pengecekan apakah diwaktu yang sudah ditentukan
            if (!dataRoom.cekWaktu(getTime())) {
                JOptionPane.showMessageDialog(this, "Anda tidak berada di waktu tapping !", null, WIDTH, null);
                return;
            }

            //cek apakah dosen atau mahasiswa dan langsung eksekusi
            if (ktm.statusOn.equals("Dosen")) {
                
                //mengecek apakah mengajar diruangan
                if (!dataRoom.cekCourse(dataLecturer.getNip(), noRuang)) {
                    JOptionPane.showMessageDialog(this, "Anda tidak mengajar di ruangan ini !", null, WIDTH, null);
                    return;
                }

                //input tapping dosen
                int baris = dataRoom.lineCourse(noRuang);
                FileWriter fw = new FileWriter("loglecturer.txt");
                PrintWriter pw = new PrintWriter(fw);
                for (int i = 1; i < 10; i++) {
                    if (i == baris) {
                        pw.println(i + " " + dataLecturer.getNip() + " 1");
                    } else {
                        pw.println(dataRoom.dataLogDosen[i]);
                    }  
                }
                pw.close();
                
                //cleartext
                dataStudent.setNim("");
                dataRoom.setRuangan("");
                dataReader.setReaderNumber("");
                dataRoom.setNama("");
                ktm.setVisible(false);
                dataReader.setVisible(false);
                
                
            } else {

                //cek apakah dosen sudah tapping
                if (!dataRoom.cekDosenTap(noRuang)) {
                    JOptionPane.showMessageDialog(this, "Dosen belum melakukan tapping !", null, WIDTH, null);
                    return;
                }

                //pengecekan apakah ada yang kosong
                if (dataStudent.getNim().equals("") || dataRoom.getRuangan().equals("") || dataReader.getReaderNumber().equals("") || dataRoom.getNama().equals("") || dataRoom.getMatkul().equals("")) {
                    JOptionPane.showMessageDialog(this, "Gagal Tapping !", null, WIDTH, null);
                    return;
                }

                //input data mahasiswa ke file
                FileWriter fw = new FileWriter("log.txt", true);
                PrintWriter pw = new PrintWriter(fw);
                //time
                pw.println(getDate() + " " + getTime());
                //nim
                pw.println(dataStudent.getNim());
                //Room
                pw.println(dataRoom.getRuangan());
                //ReaderNumber
                pw.println(dataReader.getReaderNumber());
                //Lecturer
                pw.println(dataRoom.getNama());
                //course
                pw.println(dataRoom.getMatkul());
                pw.println("-");
                pw.close();
                System.out.println("Berhasil Tapping");

                //cleartext
                dataStudent.setNim("");
                dataRoom.setRuangan("");
                dataReader.setReaderNumber("");
                dataRoom.setNama("");
                ktm.setVisible(false);
                dataReader.setVisible(false);
                
            }

            //notifikasi berhasil
            JOptionPane.showMessageDialog(this, "Berhasil Tapping", null, WIDTH, null);
            
        } catch (Exception e) {
            System.out.println("error di " + e);
        }
    }//GEN-LAST:event_btnTapActionPerformed

    private void btnRFIDReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRFIDReaderActionPerformed
        noRuang = JOptionPane.showInputDialog("Masukan Nomor Ruangan (1 - 9)");
        
        //mengoper data ruangan ke RFID reader
        int nomor = Integer.parseInt(noRuang);
        if (nomor >= 1 && nomor <= 9) {
            dataReader.setVisible(false);
            dataReader.setVisible(true);
            dataRoom.setRuangan(noRuang);
            dataReader.setReaderNumber(noRuang);
        } else {
            JOptionPane.showMessageDialog(this, "Nomor Ruangan Tidak Ditemukan", null, WIDTH, null);
        }
    }//GEN-LAST:event_btnRFIDReaderActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        //menampilkan frame history
        History table = new History();
        table.setVisible(true);
    }//GEN-LAST:event_btnHistoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCardDosen;
    private javax.swing.JButton btnCardStudent;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnRFIDReader;
    private javax.swing.JButton btnTap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
